apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: exastro-database-pvc2
  namespace: itaha01
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: exastro-database-pv2

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: exastro-file-pvc2
  namespace: itaha01
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: exastro-file-pv2
