apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: exastro-database-pvc
  namespace: itaha01
  labels:
    app: exastro-database-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: exastro-file-pvc
  namespace: itaha01
  labels:
    app: exastro-file-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
