apiVersion: v1
kind: Namespace
metadata:
  name: itaha01

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: exastro-database-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.197.17.186
    path: /exastro-database

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: exastro-file-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.197.17.186
    path: /exastro-file

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: exastro-database-pvc
  namespace: itaha01
  labels:
    app: exastro-database-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: exastro-file-pvc
  namespace: itaha01
  labels:
    app: exastro-file-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: Service
metadata:
  name: mariadb-np
  namespace: itaha01
spec:
  selector:
    app: mariadb
  ports:
  - port: 3306
    targetPort: 3306

---

apiVersion: v1
kind: Service
metadata:
  name: webapp-np
  namespace: itaha01
spec:
  selector:
    app: webapp
  ports:
  - port: 80
    nodePort: 30080
  type: NodePort

---

#apiVersion: v1
#kind: Service
#metadata:
#  name: backyard-np
#  namespace: itaha01
#spec:
#  selector:
#    app: backyard
#  ports:
#  - port: 80

---

apiVersion: v1
kind: Service
metadata:
  name: ansible-np
  namespace: itaha01
spec:
  selector:
    app: ansible
  ports:
  - name: http
    protocol: TCP
    port: 80
  - name: https
    protocol: TCP
    port: 443

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-data
  namespace: itaha01
data:
  EXASTRO_ITA_INSTALL_DIR: /exastro
  EXASTRO_ITA_DB_CONTAINER_NAME: mariadb-np
  EXASTRO_ITA_DB_USERNAME: ita_db_user

---

apiVersion: v1
kind: Secret
metadata:
  name: secret-data
  namespace: itaha01
type: Opaque
data:
  EXASTRO_ITA_DB_PASSWORD: aXRhX2RiX3Bhc3N3b3Jk

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ansible
  namespace: itaha01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ansible
  template:
    metadata:
      labels:
        app: ansible
    spec:
      containers:
      - name: ansible
        image: it-automation-ansible:1.8.1-ja-centos8
        ports:
        - containerPort: 80
        - containerPort: 443
        securityContext:
          privileged: true
        volumeMounts:
          - name: exastro-file-pv
            mountPath: /exastro-file-volume
#            mountPath: /exastro-file
      volumes:
      - name: exastro-file-pv
        persistentVolumeClaim:
          claimName: exastro-file-pvc
      terminationGracePeriodSeconds: 10

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backyard
  namespace: itaha01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backyard
  template:
    metadata:
      labels:
        app: backyard
    spec:
      containers:
      - name: backyard
        image: it-automation-backyard:1.8.1-ja-centos8
        envFrom:
        - configMapRef:
            name: cm-data
        - prefix:
          secretRef:
            name: secret-data
        ports:
        - containerPort: 80
        securityContext:
          privileged: true
        volumeMounts:
          - name: exastro-file-pv
            mountPath: /exastro-file-volume
#            mountPath: /exastro-file
      volumes:
      - name: exastro-file-pv
        persistentVolumeClaim:
          claimName: exastro-file-pvc
      terminationGracePeriodSeconds: 10

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  namespace: itaha01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        image: it-automation-mariadb:1.8.1-ja-centos8
        ports:
        - containerPort: 3306
        securityContext:
          privileged: true
        volumeMounts:
          - name: exastro-database-pv
            mountPath: /exastro-database-volume
#            mountPath: /exastro-database
      volumes:
      - name: exastro-database-pv
        persistentVolumeClaim:
          claimName: exastro-database-pvc
      terminationGracePeriodSeconds: 10

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: itaha01
spec:
#  replicas: 1
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      hostAliases:
      - ip: "127.0.0.1"
        hostnames:
        - "exastro-it-automation"
      containers:
      - name: webapp
        image: it-automation-webapp:1.8.1-ja-centos8
        envFrom:
        - configMapRef:
            name: cm-data
        - prefix:
          secretRef:
            name: secret-data
        ports:
        - containerPort: 80
        securityContext:
          privileged: true
        volumeMounts:
          - name: exastro-file-pv
            mountPath: /exastro-file-volume
      volumes:
      - name: exastro-file-pv
        persistentVolumeClaim:
          claimName: exastro-file-pvc
      terminationGracePeriodSeconds: 10
