apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        image: it-automation-mariadb:1.8.1-ja-centos8
        ports:
        - containerPort: 3306
        securityContext:
          privileged: true      
        volumeMounts:
          - name: exastro-database-volume
            mountPath: /exastro-database-volume
      volumes:
      - name: exastro-database-volume
        persistentVolumeClaim:
          claimName: exastro-database-volume
      terminationGracePeriodSeconds: 10

---

apiVersion: v1
kind: Service
metadata:
  name: mariadb-np
spec:
  selector:
    app: mariadb
  ports:
  - port: 3306
    targetPort: 3306
