apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      hostAliases:
      - ip: "127.0.0.1"
        hostnames:
        - "exastro-it-automation"
      containers:
      - name: webapp
        image: it-automation-webapp:1.8.1-ja-centos8
        ports:
        - containerPort: 80
        securityContext:
          privileged: true
        volumeMounts:
          - name: exastro-file-volume
            mountPath: /exastro-file-volume
      volumes:
      - name: exastro-file-volume
        persistentVolumeClaim:
          claimName: exastro-file-volume
      terminationGracePeriodSeconds: 10

---

apiVersion: v1
kind: Service
metadata:
  name: webapp-np
spec:
  selector:
    app: webapp
  ports:
  - port: 80
    nodePort: 30080
  type: NodePort
