apiVersion: apps/v1
kind: Deployment
metadata:
  name: ansible
  namespace: itaha01
  labels:
    app: ansible
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ansible
  template:
    metadata:
      labels:
        app: ansible
    spec:
      containers:
      - name: ansible
        image: it-automation-ansible:1.9.0-ja-centos8
        ports:
        - containerPort: 80
        - containerPort: 443
        securityContext:
          privileged: true
        volumeMounts:
          - name: exastro-file-pv
            mountPath: /exastro-file-volume
      volumes:
      - name: exastro-file-pv
        persistentVolumeClaim:
          claimName: exastro-file-pvc
      terminationGracePeriodSeconds: 10

---

